# Site settings
title: Creductive Web developer
description: 창조적이고 생산적이고 싶은 개발자의 블로그
baseurl: ""
url: "https://blog.creductive.com"

# User settings
username: koamania
user_description: Web devloper
email: koamania2@gmail.com
twitter_username: 
github_username:  koamania

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
